version: 2.1


# - Scalar variables -
scalar-1: &node_modules_cache_key aurelia-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

scalar-2: &working_dir ~/repo

# - Map variables -
map-1: &package_globs
  paths:
    - dist
    - packages/*/dist
    - packages/*/node_modules

# - Executors -
executors:

  docker-circleci:
    working_directory: *working_dir
    docker:
      - image: "circleci/node:10.12-stretch-browsers"

  docker-aurelia:
    working_directory: *working_dir
    docker:
      - image: "aureliaeffect/circleci-v2:latest"


# - Commands -
commands:

  # first_* commands are initializers for jobs, they must come first
  first_npm_install:
    description: "Run npm install"
    steps:
      - checkout
      - run:
          name: "Run npm install"
          command: npm ci --ignore-scripts

  # implies first_npm_install
  first_restore_cache:
    description: "Restore node_modules from cache"
    steps:
      - checkout
      - restore_cache:
          key: *node_modules_cache_key

  # implies first_restore_cache
  first_attach_workspace:
    description: "Attach persisted packages from workspace"
    steps:
      - first_restore_cache
      - attach_workspace:
          at: *working_dir

  # first_* commands are finalizers for jobs, they must come last
  last_save_cache:
    description: "Save node_modules to cache"
    steps:
      - save_cache:
          key: *node_modules_cache_key
          paths:
            - node_modules

  last_persist_workspace:
    description: "Persist packages to workspace"
    steps:
      - persist_to_workspace:
          root: *working_dir
          <<: *package_globs

  # do_* commands are arbitrary commands that run in-between first and last
  do_build_packages:
    description: "Bootstrap and build packages"
    steps:
      - run:
          name: "Bootstrap packages"
          command: npm run bootstrap
      - run:
          name: "Build packages"
          command: npm run build

  do_bundle_packages:
    description: "Bundle packages"
    steps:
      - run:
          name: "Bundle packages"
          command: npm run bundle:all

  do_lint_packages:
    description: "Lint packages"
    steps:
      - run:
          name: "Lint packages"
          command: npm run lint

  do_merge_push:
    description: "Merge and push"
    parameters:
      from:
        type: string
      to:
        type: string
    steps:
      - run:
          name: "Checkout << parameters.to >>"
          command: git checkout << parameters.to >>
      - run:
          name: "Merge << parameters.from >> into << parameters.to >>"
          command: git merge << parameters.from >> --no-ff --no-edit -Xtheirs
      - run:
          name: "Push << parameters.to >>"
          command: git push origin << parameters.to >>

# - Jobs -
jobs:

  # Must come before any other job
  install_root:
    executor: docker-circleci
    steps:
      - first_npm_install
      - last_save_cache

  # Requires install_root
  build_packages:
    executor: docker-circleci
    steps:
      - first_restore_cache
      - do_build_packages
      - last_persist_workspace

  # Requires install_root
  lint_packages:
    executor: docker-circleci
    steps:
      - first_restore_cache
      - do_lint_packages

  # Requires build_packages
  bundle_packages:
    executor: docker-circleci
    steps:
      - first_attach_workspace
      - do_bundle_packages
      - last_persist_workspace

  # Requires bundle_packages
  merge_to_develop:
    executor: docker-circleci
    steps:
      - first_attach_workspace
      - do_merge_push:
          from: master
          to: develop

  job1:
    machine: true
    parameters:
      job1p1:
        type: string
        default: "Default"
    steps:
      - run: echo  "job1p1= << parameters.job1p1 >>"

# - Workflows -
workflows:
  build_test_dev:
    jobs:
      - install_root:
          filters:
            branches:
              ignore:
                - develop
                - release
      - build_packages:
          requires:
            - install_root
          filters:
            branches:
              ignore:
                - develop
                - release
      - lint_packages:
          requires:
            - install_root
          filters:
            branches:
              ignore:
                - develop
                - release
      - bundle_packages:
          requires:
            - build_packages
          filters:
            branches:
              only: master
      - merge_to_develop:
          requires:
            - bundle_packages
          filters:
            branches:
              only: master

  # wf2:
  #   triggers:
  #     - schedule:
  #         cron: "0 * * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master

  #   jobs:
  #     - job1:
  #         job1p1: "from wf2"
